Global:
  BaseProbability: 0.1
  LogLevelGlobal: ALL    # Possible Values:  ALL, DEBUG, INFORMATION, WARNING, ERROR, NONE
  LogLevelBeehive: DEBUG   # Possible Values:  ALL, DEBUG, INFORMATION, WARNING, ERROR, NONE
Hard:
  FieldProperties:
    flowerable: 1
    walkable:   8
    flyable:    9
Medium:
  FieldProperties:
    flowerable: 2
    walkable:   8
    flyable:    9
Easy:
  FieldProperties:
    flowerable: 3
    walkable:   8
    flyable:    9
