Global:
  BaseProbability: 0.1
  LogLevel: DEBUG    # Possible Values:  ALL, DEBUG, INFO, WARNING, ERROR, NONE
Hard:
  FieldProperties:
    flowerable: 1
    walkable:   8
    flyable:    9
Medium:
  FieldProperties:
    flowerable: 2
    walkable:   8
    flyable:    9
Easy:
  FieldProperties:
    flowerable: 3
    walkable:   8
    flyable:    9
